version: '3.8'
services:
  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app # 挂载完整代码库，保持 backend 包路径一致
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    restart: unless-stopped
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  # 前端服务 (用一个简单的Nginx来托管)
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped

  # Redis 消息队列
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # Celery 计算节点 (需要GPU支持)
  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - redis
    # GPU support (optional)
    runtime: nvidia
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    restart: unless-stopped
    command: celery -A backend.celery_app.celery_app worker -l info --concurrency=1

volumes:
  redis-data:
